#!/bin/bash
set -euo pipefail

aws iam create-role \
  --role-name GitHubActions4WaterPlannerCoreDeploymentRole \
  --assume-role-policy-document file://trust-policy.json


aws iam attach-role-policy \
  --role-name GitHubActions4WaterPlannerCoreDeploymentRole \
  --policy-arn arn:aws:iam::aws:policy/AdministratorAccess